project_id = "dibsaswbhkryxhsxxmiv"

[functions.send-email]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.reset-password-email]
verify_jwt = false

[functions.manage-users]
verify_jwt = false